springfoxdocumentation:
  swagger:
    v2:
      path: /api-docs

server:
  port: ${PETSTOREPRODUCTSERVICE_SERVER_PORT:8080}

spring:
  datasource:
    primary:
      url: ${PETSTOREPRODUCTSERVICE_DB_URL:}
      username: ${PETSTOREPRODUCTSERVICE_DB_USER:docker}
      password: ${PETSTOREPRODUCTSERVICE_DB_PASSWORD:SQL}
      hikari:
        poolName: primary-connection-pool
        minIdle: 10
        maxPoolSize: 15
    liquibase:
      url: ${PETSTOREPRODUCTSERVICE_LIQUIBASE_DB_URL:}
      username: ${PETSTOREPRODUCTSERVICE_LIQUIBASE_DB_USER:docker}
      password: ${PETSTOREPRODUCTSERVICE_LIQUIBASE_DB_PASSWORD:SQL}
      hikari:
        poolName: liquibase-connection-pool
        minIdle: 0
        maxPoolSize: 1

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: petstoreproductservice
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

azure:
  application-insights:
    instrumentation-key: ${APPINSIGHTS_INSTRUMENTATIONKEY:}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  trace:
    http:
      enabled: true
  endpoint:
    httptrace:
      enabled: true