version: "3.9"

services:

  petstoreapp:
    build:
      context: ./petstoreapp
    ports:
      - "8080:8080"
    environment:
      - PETSTOREAPP_SERVER_PORT=8080
      - PETSTOREPETSERVICE_URL=http://petstorepetservice:8081
      - PETSTOREPRODUCTSERVICE_URL=http://petstoreproductservice:8082
      - PETSTOREORDERSERVICE_URL=http://petstoreorderservice:8083
      - ORDER_ITEMS_RESERVE_URL=http://order-items-reserve:8084
    networks:
      - petstorebridge

  petstorepetservice:
    build:
      context: ./petstorepetservice
    ports:
      - "8081:8081"
    environment:
      - PETSTOREPETSERVICE_SERVER_PORT=8081
    networks:
      - petstorebridge

  petstoreproductservice:
    build:
      context: ./petstoreproductservice
    ports:
      - "8082:8082"
    environment:
      - PETSTOREPRODUCTSERVICE_SERVER_PORT=8082
    networks:
      - petstorebridge

  petstoreorderservice:
    build:
      context: ./petstoreorderservice
    ports:
      - "8083:8083"
    environment:
      - PETSTOREORDERSERVICE_SERVER_PORT=8083
      - PETSTOREPRODUCTSERVICE_URL=http://petstoreproductservice:8082
    networks:
      - petstorebridge

#  order-items-reserve:
#    image: order-items-reserve:latest
#    ports:
#      - "80:80"
#    environment:
#      - AZURE_STORAGE_CONNECTION_STRING="UseDevelopmentStorage=true;DevelopmentStorageProxyUri=http://host.docker.internal"
#      - AzureWebJobsStorage="UseDevelopmentStorage=true;DevelopmentStorageProxyUri=http://host.docker.internal"
#    networks:
#      - petstorebridge
#
#  azure-blob-storage:
#    image: mcr.microsoft.com/azure-storage/azurite:latest
#    ports:
#      - "10000:10000"
#      - "10001:10001"
#      - "10002:10002"
#    volumes:
#      - data-volume-azurite:/opt/azurite/folder

networks:
  petstorebridge:
    driver: bridge

#volumes:
#  data-volume-azurite: